# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy_github:
          context: org-global
          filters:
            branches:
              ignore: /pull\/.*/
            tags:
              only: /.*/
          requires:
            - build
      - deploy_surge:
          context: org-global
          filters:
            branches:
              only: /pull\/.*/
          requires:
            - build

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

env: &env
  run:
    name: set environment variables
    command: |
      echo export\ MERGE_PR_NUMBER=$(git log --oneline --merges --pretty=format:"%s" --grep="Merge pull request" -n 1 ${CIRCLE_SHA1} | sed 's/from.*//' | sed -e 's/.*[^0-9]\([0-9]\+\)[^0-9]*$/\1/') >> $BASH_ENV
      echo export\ COMMIT_MSG=\"$(git log --oneline --pretty=format:"%s" -n 1 $CIRCLE_SHA1)\" >> $BASH_ENV

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: |
          sudo npm i npm@latest -g
          npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
        
      # build
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .vuepress/dist
      - run: npm audit

  deploy_github:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/repo
        - run:
            name: Login
            command: |
              git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
              git config --global user.name "$GH_NAME" > /dev/null 2>&1
              # https://discuss.circleci.com/t/git-clone-fails-in-circle-2-0/15211/2
              mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        - run:
            name: Deploy to edi-things.github.io
            command: |
              cd .vuepress/dist
              git init
              git add -A
              git commit -m 'deploy'
              git push -f git@github.com:edi-things/edi-things.github.io.git master

        # Teardown When PR is Merged
        - checkout
        - <<: *env
        - run: 
            name: teardown preview docs if it is merged PR
            command: |
              if [[ $MERGE_PR_NUMBER ]]; then
                npm i -g surge;
                surge teardown ${CIRCLE_PROJECT_REPONAME}-$MERGE_PR_NUMBER.surge.sh;
              fi

  deploy_surge:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/repo
        - checkout
        - <<: *env
        - run: npm i -g surge
        - run: surge .vuepress/dist --domain ${CIRCLE_PROJECT_REPONAME}-$CIRCLE_PR_NUMBER.surge.sh